# argv3 is QT_ANDROID_APP_PATH
set(QT_ANDROID_APP_PATH ${CMAKE_ARGV3})
# argv4 is QT_ANDROID_APP_PATH
configure_file(${CMAKE_CURRENT_BINARY_DIR}/qtdeploy.json.in ${CMAKE_CURRENT_BINARY_DIR}/qtdeploy.json @ONLY)